#! /bin/sh

sxhkd &
dunst &
panel &
#pgrep -x panel > /dev/null || panel &

. panel_colors

bspc monitor HDMI-A-0 -d 1 2 3 4 5
bspc monitor VGA-0 -d 1 2 3 4 5

bspc config border_width 3
bspc config window_gap 0
bspc config focused_border_color "#d75f00" 
bspc config normal_border_color "#cac9c9"
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
