#! /bin/sh
# Panel for lemonbar

. panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
  case $line in
    S1*)
      sys_first=" ${line#??} "
      ;;
    S2*)
      sys_second=" ${line#??} "
      ;;
    T*)
      title="%{F$COLOR_DEFAULT_FG}%{B$COLOR_DEFAULT_BG} ${line#?} %{B-}%{F-}"
      ;;
    W*)
      wm=
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          [mM]*)
            case $item in
              m*)
                on_focused_monitor=
                ;;
              M*)
                on_focused_monitor=1
                ;;
            esac
            [ $num_mon -lt 2 ] && shift && continue
            wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
            ;;
          [fFoOuU]*)
            case $item in
              [FOU]*)
                [ "$on_focused_monitor" ] && name="°${name}"
                ;;
            esac
            wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
            ;;
          G*)
            [ -z ${name} ] && name='-'
            wm="${wm}%{F$COLOR_DEFAULT_FG}%{B$COLOR_DEFAULT_BG} ${name} %{B-}%{F-}"
            ;;
        esac
        shift
      done
      ;;
  esac
  
  button="%{A:xterm:}%{A}"  
  sys="${sys_second}/${sys_first}"
  printf "%s\n" "%{l}${wm}${button}%{c}${title}%{r}${sys}"
done
